{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "16036e14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10 20 30 40 \n"
     ]
    }
   ],
   "source": [
    "#واجب طباعة الطابور\n",
    "\n",
    "\n",
    "class Node:\n",
    "    def __init__(self, data):\n",
    "        self.data = data\n",
    "        self.next = None\n",
    "\n",
    "class LinkedList:\n",
    "    def __init__(self):\n",
    "        self.head = None\n",
    "        self.tail = None\n",
    "        self.length = 0\n",
    "\n",
    "    def is_empty(self):\n",
    "        return self.length == 0\n",
    "\n",
    "    def insert_first(self, data):\n",
    "        new_node = Node(data)\n",
    "        if self.is_empty():\n",
    "            self.head = self.tail = new_node\n",
    "        else:\n",
    "            new_node.next = self.head\n",
    "            self.head = new_node\n",
    "        self.length += 1\n",
    "\n",
    "    def insert_last(self, data):\n",
    "        new_node = Node(data)\n",
    "        if self.is_empty():\n",
    "            self.head = self.tail = new_node\n",
    "        else:\n",
    "            self.tail.next = new_node\n",
    "            self.tail = new_node\n",
    "        self.length += 1\n",
    "\n",
    "    def insert_at_pos(self, pos, data):\n",
    "        if pos < 0 or pos > self.length:\n",
    "            print(\"Out of range\")\n",
    "            return\n",
    "        if pos == 0:\n",
    "            self.insert_first(data)\n",
    "        elif pos == self.length:\n",
    "            self.insert_last(data)\n",
    "        else:\n",
    "            new_node = Node(data)\n",
    "            current = self.head\n",
    "            for _ in range(pos - 2):\n",
    "                current = current.next\n",
    "            new_node.next = current.next\n",
    "            current.next = new_node\n",
    "            self.length += 1\n",
    "\n",
    "    def print_list(self):\n",
    "        current = self.head\n",
    "        while current:\n",
    "            print(current.data, end=\" \")\n",
    "            current = current.next\n",
    "        print()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    l = LinkedList()\n",
    "    l.insert_first(10)\n",
    "    l.insert_last(30)\n",
    "    l.insert_last(40)\n",
    "    l.insert_at_pos(2, 20)\n",
    "    l.print_list()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# In[6]:\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "32e323e3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "50\n",
      "940\n",
      "96\n",
      "النتيجة بعد الحذف\n",
      "940\n",
      "96\n"
     ]
    }
   ],
   "source": [
    "#واجب دالة للبحث عن قيمة وحذفها\n",
    "class Node:\n",
    "    def __init__(self, data):\n",
    "        self.data = data\n",
    "        self.next = None\n",
    "\n",
    "class LinkedList:\n",
    "    def __init__(self):\n",
    "        self.head = None\n",
    "\n",
    "    def print_list(self):\n",
    "        if self.head is None:\n",
    "            print('Linked list is empty')\n",
    "        else:\n",
    "            currentNode = self.head\n",
    "            while currentNode is not None:\n",
    "                print(currentNode.data)\n",
    "                currentNode = currentNode.next\n",
    "\n",
    "    def add_begin(self, data):\n",
    "        new_node = Node(data)\n",
    "        new_node.next = self.head\n",
    "        self.head = new_node\n",
    "#===============================================\n",
    "    def delete_node(self, key):\n",
    "        currentNode = self.head\n",
    "\n",
    "        if currentNode is not None:\n",
    "            if currentNode.data == key:\n",
    "                self.head = currentNode.next\n",
    "                currentNode = None\n",
    "                return\n",
    "\n",
    "        prev = None\n",
    "        while currentNode is not None:\n",
    "            if currentNode.data == key:\n",
    "                break\n",
    "            prev = currentNode\n",
    "            currentNode = currentNode.next\n",
    "\n",
    "        if currentNode is None:\n",
    "            print(\"Element not found in the list.\")\n",
    "            return\n",
    "\n",
    "        prev.next = currentNode.next\n",
    "        currentNode = None\n",
    "#======================================================\n",
    "list = LinkedList()\n",
    "list.add_begin(96)\n",
    "list.add_begin(940)\n",
    "list.add_begin(50)\n",
    "list.print_list()\n",
    "\n",
    "print('النتيجة بعد الحذف')\n",
    "\n",
    "list.delete_node(50)\n",
    "list.print_list()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "369ff070",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
